title: Page title by me.
author: David Pinto
email: davidpinto1979@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Description for my new site in GitHub. Line edited in _config.yml.
  Appears in document head meta (for Google search results)
  and in feed.xml site description.

theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
